// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function isFizz(n) {
  return n % 3 === 0;
}

function isBuzz(n) {
  return n % 5 === 0;
}

function fizzBuzz(n) {
  var match = isFizz(n);
  var match$1 = isBuzz(n);
  if (match) {
    if (match$1) {
      return "FizzBuzz";
    } else {
      return "Fizz";
    }
  } else if (match$1) {
    return "Buzz";
  } else {
    return n.toString();
  }
}

Belt_Array.forEach(Belt_Array.map(Belt_Array.range(1, 100), fizzBuzz), (function (prim) {
        console.log(prim);
        
      }));

exports.isFizz = isFizz;
exports.isBuzz = isBuzz;
exports.fizzBuzz = fizzBuzz;
/*  Not a pure module */
