// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("rescript/lib/js/string.js");
var Js_math = require("rescript/lib/js/js_math.js");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Pervasives = require("rescript/lib/js/pervasives.js");

console.log("Guess the number!");

var secretNumber = Js_math.random_int(1, 101);

function game(_param) {
  while(true) {
    console.log("Please input your guess.");
    var guess = Belt_Int.fromString($$String.trim(Pervasives.read_line(undefined)));
    if (guess !== undefined) {
      console.log("You guessed: " + String(guess));
      if (guess < secretNumber) {
        console.log("Too small!");
        _param = undefined;
        continue ;
      }
      if (guess > secretNumber) {
        console.log("Too big!");
        _param = undefined;
        continue ;
      }
      console.log("You win!");
      return ;
    }
    _param = undefined;
    continue ;
  };
}

game(undefined);

exports.secretNumber = secretNumber;
exports.game = game;
/*  Not a pure module */
